### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zmrocze** [mlabs-haskell/the-plutus-scaffold#3]
# mlabs-plutus-template Roadmap

- [ ] **Stage 1**
  - onchain
  - [X] Example onchain with AlwaysSucceeds
    - [ ] #12 
    - [X] Plutarch
  - [x] script builder producing json mapping and directory with CBOR scripts
  - offchain
    - [ ] Debug Contract execution in terminal on plutip cluster (modified, comment below)
      - [ ] Submit script transaction example contract (wallet?)
  - tools
    - [x] formatters, build
    - [x] ply
    - [ ] hoogle
    - [x] pursuit
    - [X] GH commit hooks
- [ ] **Stage 2** (80 hours)
  - onchain
    - [x] plutus-simple-model example test suite
    - [x] Applied scripts examples, scripts dependant on previous script hashes
  - offchain
    - [ ] e2e contract execution test suite in the headless browser
      - [x] plutip
      - [ ] public testnet
    - [x] pain-free on-chain script importing
      - [x] auto-generated imports into offchain
      - [x] restore script type information with ply-ctl (investigate) (#1 )
  -  tools 
    - [ ] CI executes e2e plutip tests
  - frontend
    - [x] #5
    - [ ]  ̶C̶o̶n̶f̶i̶g̶u̶r̶a̶b̶l̶e̶ ̶e̶x̶e̶c̶u̶t̶i̶o̶n̶ ̶b̶a̶c̶k̶e̶n̶d̶?̶  (removed, comment below)
- [ ] **Stage 3**
  - offchain
    - [ ] deployment scripts
      - [ ] example cluster deploy on _ cloud provider (terraform?)
        - [x] #13
        - [ ] proxy redirects queries to ctl-runtime
        - [ ] on (public) testnet
          - [ ] with public blockfrost
          - [ ] with self-hosted ctl-runtime
      - [ ] metrics
        - [ ] nginx metrics for frontend
        - [ ] + frontend react metrics
        - [ ] + indexers metrics (investigate)
      - [ ] #11
      - [ ] + example herculesCI effect deploying frontend to gh pages, running on some testnet (testnet funds?)
      - [ ] + blockfrost keys proxied from somewhere (just our side, no production ready keystore setup)
  - frontend
    - [ ] load balancer, credentials (?)
- [ ] **Stage 4**
  - offchain
    - [ ] custom indexers
    - [ ] proxy for Blockfrost keys (moved to stage 3)
    - [ ] dos protection for kupo and ogmios (moved to stage 3)

**Comment by zmrocze** [comment]
removed:  ̶C̶o̶n̶f̶i̶g̶u̶r̶a̶b̶l̶e̶ ̶e̶x̶e̶c̶u̶t̶i̶o̶n̶ ̶b̶a̶c̶k̶e̶n̶d̶?̶
why?:  Writing this I had on mind choosing plutip vs testnet. But offchain and frontend code is mostly blind to the distinction as its wallet (and indexers) choosing the network. Currently there is no easy way outside of ctl e2e tests to run on plutip (or other) local-cluster. Of course there will be e2e plutip test suite (using ctl's machinery).

modified: 
`
CTL contracts execution from the browser (on plutip network),
list of endpoints to run listed contracts
(Actual browser or headless in terminal?)
`
    changes to  =>
`
Debug Contract execution in terminal on plutip cluster
`
why?: With this point I meant some pain-free way for print-style debugging of offchain code, what I was missing in ctl. Should be possible to modify e2e test suite to allow for such an example.

**Comment by zmrocze** [comment]
## ctl-runtime vs blockfrost self-hosted vs blockfrost public
 Currently devops lacks nixos blockfrost module to self-host it (on the way: [link](https://github.com/mlabs-haskell/devops/issues/302)), so I'd skip this option for now (also on our side its almost same as blockfrost public).
 
But I'd provide both options: `blockfrost public` and `ctl-runtime`. On our side this mostly means two versions of ctl's `ContractParams`, two frontend executables for bundler and two versions of deployment parameters.
